export enum ConditionOperator {
    EQUALS = '$eq',
    NOT_EQUALS = '$ne',
    GREATER_THAN = '$gt',
    LESS_THAN = '$lt',
    GREATER_THAN_EQUALS = '$gte',
    LESS_THAN_EQUALS = '$lte',
    STARTS = '$starts',
    ENDS = '$ends',
    CONTAINS = '$cont',
    EXCLUDES = '$excl',
    IN = '$in',
    NOT_IN = '$notin',
    IS_NULL = '$isnull',
    NOT_NULL = '$notnull',
    BETWEEN = '$between',
    EQUALS_LOW = '$eqL',
    NOT_EQUALS_LOW = '$neL',
    STARTS_LOW = '$startsL',
    ENDS_LOW = '$endsL',
    CONTAINS_LOW = '$contL',
    EXCLUDES_LOW = '$exclL',
    IN_LOW = '$inL',
    NOT_IN_LOW = '$notinL'
}
